var Crawler = require("crawler");
var url = require('url');
var fs = require('fs');
var http = require('http');


function saveImg(imgUrl, fileName) {
    var extension = imgUrl.match(/.*(\.[a-zA-Z]+)$/)[1];

    try{
        http.get(imgUrl, function (res) {
            var file = fs.createWriteStream('./logos/' + (fileName || res.client._host) + extension);
            res.on('data', function (data) {
                file.write(data);
            }).on('end', function () {
                file.end();
                console.log(fileName + ' downloaded ');
            });
        });
    }catch(err){
        console.log(err);
    }
}


var c = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: function (error, res, done) {
        if (error) {
            console.log(error);
        } else {
            var $ = res.$;
            if(!$){
                console.log('ERROR: could not find ' + findByUrl(res.request.host));
                done();
                return;
            }

            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log('------------------------');
            var sectionKey = findByUrl(res.request.host);
            console.log('fetching Section : ' + sectionKey);
            console.log('URL : ' + res.request.href);

            //extract logo

            var search = $("#logo").find('img');
            if (search.length != 0) {
                var imgUrl = search[0].attribs.src;
                console.log(imgUrl);
                saveImg(imgUrl, sectionKey)
            }


        }
        done();
    }
});

//raw urls from api
var urls = ["", "http://unigraz.esnaustria.org/welcome-esn-uni-graz", "http://innsbruck.esnaustria.org/", "www.entree.at", "http://www.krems.esnaustria.org/", "", "", "http://esnlinz.org", "http://salzburg.esnaustria.org/", "", "", "http://oehmedwien.at/", "http://technikum.esnaustria.org", "www.buddynetwork.at", "http://bfivienna.esnaustria.org", "http://www.esnuniwien.com/", "www.fhwien-wkw.esnaustria.org/", "baku.esn.az", "esn-bih.ba", "esnantwerp.org", "http://www.esnkulbrussels.org/", "esnvubehb.org", "none (yet)", "", "", "", "http://www.esnleonardokortrijk.org/", "www.esnleuven.be", "esnulg.org", "http://esn.hec-ulg.be/", "https://esnhelmo.wordpress.com/ or https://www.helmo.be/CMS/Profils/International/FR/ESN.aspx", "", "http://esnlln.org/", "None yet", "", "none", "plovdiv.esnbg.org", "", "", "", "", "uaceg.esnbg.org", "http://unwe.esnbg.org/", "http://varna.esnbg.org/", "http://tarnovo.esnbg.org/", "", "www.bern.esn.ch", "htwchur.esn.ch", "fribourg.esn.ch", "http://geneva.esn.ch/", "http://epfl.esn.ch/", "", "lugano.esn.ch", "", "olten.esn.ch", "http://www.ressortinternational.ch/portfolio/buddysystem/", "http://winterthur.esn.ch", "/", "http://zurich.esn.ch/", "zurich.esn.ch", "www.esncy.org", "http://isc.muni.cz/", "www.isc.vutbr.cz", "www.esnvste.cz", "www.buddyhk.cz", "http://www.esn-liberec.cz/", "http://iscmendelu.cz/", "http://esn.upol.cz", "http://isc.osu.cz/", "www.esnvsb.cz", "http://http://esn.upce.cz/", "http://www.esn.zcu.cz", "www.isc.cvut.cz", "http://esnculs.cz/", "www.ic-cuni.cz", "http://www.esnuct.cz/", "buddy.vse.cz", "www.esn-usti.cz", "www.buddysystem.utb.cz", "http://augsburg.esn-germany.de/", "http://bayreuth.esn-germany.de/", "", "bochum@esngermany.org", "www.esn-bonn.de", "http://braunschweig.esn-germany.de", "http://www.aki-deggendorf.de/in/", "dortmund.esn-germany.de", "http://faranto.esn-germany.de/", "http://tu-dresden.esn-germany.de/?language=en", "www.duesseldorf.esn-germany.de", "http://www.interstudis.eu/", "", "http://unifrankfurt.esn-germany.de", "http://greifswald.esn-germany.de/", "halle.esn-germany.de", "http://hamburg.esn-germany.de/de", "hannover.esn-germany.de", "www.esn-heidelberg.de", "hildesheim.esn-germany.de", "ingolstadt.esngermany.org", "http://jena.esn-germany.de/", "www.step.wiwi.uni-kl.de", "www.ak-erasmus.de", "koeln.esn-germany.de", "landau.esn-germany.de", "https://www.visum-mannheim.de/satellite4/", "http://mesa.esn-germany.de/", "www.international.tum.de/tumi", "http://potsdam.esn-germany.de/", "www.lei-rostock.org", "", "http://esn-cph.dk", "", "", "www.esn-dtu.dk/", "www.esnodense.dk", "http://esn.ee/tallinn", "https://www.esindus.ee/ic", "http://ic.tipikas.ee/", "https://esn.ee/tartu", "www,esn-uah.org", "", "www.esnalmeria.org", "http://www.esnuex.org/", "http://esn-ub.org/", "http://esnupf.org/", "http://esnuab.org", "http://www.esn-upc.org/", "http://esnbilbao.org/", "http://www.esncadiz.org/", "www.esncartagena.org", "http://esncastellon.org/", "www.esncoruna.org", "", "www.udg.edu/esngirona ", "www.esngranada.org", "", "www.esnjaen.org", "http://esnuc3m.org/", "http://www.esnurjc.es/", "http://esnuam.org/", "Www.esnucm.org", "www.esnmalaga.org", "www.esnmurcia.es", "www.esnoviedo.org", "", "http://esnsalamanca.com/", "http://esnsevilla.org", "http://www.esnuclm.org/", "http://esnuv.es", "http://esnvalenciaupv.es/", "http://www.esnuva.org/", "www.esnuax.org", "www.esnvigo.org/satellite4", "www.esnzaragoza.orh", "esnunihelsinki.com", "www.esn-helga.com", "http://esn.metropolia.fi/", "esnaalto.org", "http://esnjoensuu.fi/", "http://www.esnjyvaskyla.org", "www.esnkisa.eu", "", "esnoulu.org", "www.esnlapland.eu", "www.esninto.org", "www.esnfint.org", "https://esnabo.org/", "esn-iac.org", "www.esnuniturku.fi", "www.esnvaasa.net", "amiens.ixesn.fr", "http://avignon.ixesn.fr", "http://belfort-montbeliard.ixesn.fr/", "www.erasmus-besancon.com", "bordeaux.ixesn.fr", "", "http://worldtop.ixesn.fr/", "", "", "http://dijon.ixesn.fr/", "http://esnlille.fr/satellite/", "www.lyon.ixesn.fr", "lemans.ixesn.fr", "marseille.ixesn.fr", "http://montpellier.ixesn.fr", "www.esnnancy.fr", "", "", "http://nice.ixesn.fr/", "orleans.ixesn.fr", "http://paris.ixesn.fr/", "", "", "http://poitiers.ixesn.fr/", "aix.ix.fr", "ereimsmus.eu", "http://rennes.ixesn.fr/", "http://www.larochelle.ixesn.fr/", "www.rouen.ixesn.fr", "", "http://strasbourg.ixesn.fr/", "http://www.toulouse.ixesn.fr", "", "", "", "http://valence.ixesn.fr/", "http://rgu.esnuk.org/", "", "bristol.esnuk.org", "cardiff.esnuk.org", "http://hw.esnuk.org/", "gcu.esnuk.org", "uofg.esnuk.org", "", "herts.esnuk.org", "http://kings.esnuk.org", "www.luu.org.uk/groups/interasoc/", "", "", "NA", "imperial.esnuk.org", "http://westminster.esnuk.org/", "", "http://plymouth.esnuk.org/", "http://uclan.esnuk.org/", "http://soton.esnuk.org/", "", "", "", "", "http://aueb.esnathens.gr/", "", "http://esnkapa.org/athens/", "http://panteion.esngreece.gr/", "http://esn.teipir.gr/", "http://teiath.esngreece.gr/", "http://tuc.esngreece.gr/", "", "http://uoc.esngreece.gr/", "http://ioannina.esngreece.gr/", "http://duth.esngreece.gr/", "https://www.facebook.com/ESNTEIWM/?fref=ts", "http://teiste.esngreece.gr/", "http://larissa.esngreece.gr/", "", "http://ntua.esngreece.gr/", "http://uopa.esngreece.gr/", "http://unipi.esngreece.gr/", "http://auth.esngreece.gr/", "http://uom.esngreece.gr/", "http://ateith.esngreece.gr/", "www.esndubrovnik.hr", "", "esn.hr", "esnsplit.com", "", "", "", "https://www.esn.bme.hu/", "http://corvinus.esn.hu/", "http://elte.esn.hu/", "http://ibs.esn.hu/", "http://nups.esn.hu/", "http://obuda.esn.hu/", "http://debrecen.esn.hu/", "eger.esn.hu", "szie.esn.hu", "http://sze.esn.hu/", "http://miskolc.esn.hu/", "http://pecs.esn.hu/", "http://semmelweis.esn.hu/", "www.szeged.esn.hu", "", "", "", "", "", "esn.is", "N/A", "http://www.esnancona.it", "http://www.esnlaquila.it/", "www.esnbari.org", "", "http://www.esnbergamo.it/", "www.esnbocconi.it", "http://www.esnbologna.org/", "http://www.esnbrescia.it/", "www.esncagliari.org ", "www.esncamerino.it", "www.esncastellanza.it", "http://www.esncatania.it/", "www.esncosenza.org", "www.esncatanzaro.com", "www.esnferrara.org", "http://www.esnflorentia.it", "www.esnfoggia.it", "", "www.erasmuslecce.it", "www.esnmacerata.it", "http://www.esn-messina.it", "http://www.esnbicocca.it/bicocca", "http://www.esniulm.it", "http://www.esnpolimi.it/", "http://www.esnmilanostatale.it/", "www.esnunicatt.it", "www.esnmodena.it", "", "http://piemonteorientale.org/", "http://sat4.esnpadova.eu/?q=events/feed", "", "assi.unipr.it", "http://www.esnpavia.org/", "http://www.perugiaerasmusproject.eu", "www.esnchietipescara.eu", "www.esnpisa.it", "http://www.esnsuigenerisbas.it/", "http://www.esnreggiocalabria.org/", "www.esnrimini.it", "", "http://www.esnromaluiss.it/", "http://www.esnroma3.com/", "http://www.esnsalerno.it/", "", "", "www.esnnaseudine.it", "esnteramo.eu", "www.esntrento.it", "http://esntrieste.it/", "", "http://www.ase-esnverona.it/", "www.esn.li", "http://ktu.esnlithuania.org/", "http://esnlithuania.org/sections/esn-kk", "", "", "vmu.esnlithuania.org", "", "", "vu.esnlithuania.org", "", "http://ism.esnlithuania.org", "http://leu.lt/lt/esn-leu/esn-naujienos.html", "http://mru.esnlithuania.org/", "", "http://vdk.esnlithuania.org/", "", "www.esn.lu", "https://www.facebook.com/Erasmusjelgava/", "", "http://riga.esn.lv/", "https://www.facebook.com/ESNvalmiera/?ref=bookmarks", "", "/", "esnmalta.org", "http://isn-amsterdam.nl/", "http://esnvuamsterdam.nl/", "www.esn-breda.nl", "www.esn-delft.nl/", "", "esntwente.nl", "www.esn-groningen.nl", "esnhaarlem.nl", "www.esn-leeuwarden.com", "www.isnleiden.com", "isn-maastricht.nl", "www.esn-rotterdam.nl", "http://www.esnrotterdam.nl", "www.iesntilburg.nl", "www.esn-utrecht.nl", "http://ixesn-wageningen.nl/", "https://www.facebook.com/groups/121550639157/?fref=ts", "http://www.as.esn.no/", "http://www.bergen.esn.no/", "http://agder.esn.no", "www.molde.esn.no", "http://www.oslo.esn.no/", "", "www.trondheim.esn.no", "http://pb.esn.pl/", "http://uwb.esn.pl", "http://www.ukw.edu.pl/jednostka/erasmus_student_network/", "http://pcz.esn.pl", "http://gdansk.esn.pl/", "http://ug.esn.pl", "", "http://sut.esn.pl/", "", "", "http://uek.esn.pl/", "http://agh.esn.pl/", "http://www.pk.esn.pl/", "http://uj.esn.pl/", "", "eye.esn.pl", "lodz.esn.pl", "http://www.lut.esn.pl/", "umcs.esn.pl", "http://uwm.esn.pl/pl", "", "http://esnpoznan.pl/", "www.uam.esn.pl ", "", "NA", "we dont have", "http://szczecin.esn.pl/", "", "", "cc.esn.pl", "-", "lazarski.esn.pl", "esnsgh.pl", "http://sggw.esn.pl/", "swps.esn.pl", "www.uksw.esn.pl", "www.uw.esn.pl", "www.pw.esn.pl", "http://pwr.esn.pl/", "http://uewroclaw.esn.pl/", "http://up.esn.pl/", "www.facebook.com/esn.uwr", "http://www.esnaveiro.org", "www.esnbraganca.org", "", "http://www.esncoimbra.org/", "www.esn-covilha.org", "www.esnevora.org", "http://www.esnalgarve.org/", "www.esnmadeira.org", "http://esnleiria.com/", "http://esnlisboa.org/", "http://www.esnminho.org/", "esnporto.org", "", "esnutad.org", "http://alba-iulia.esn.ro/", "", "www.ase-bucharest.esn.ro", "http://unibucharest.esn.ro/", "http://cluj-napoca.esn.ro/", "http://esn.ro/constanta/", "http://craiova.esn.ro", "http://iasi.esn.ro/", "sibiu.esn.ro", "www.timisoara.esn.ro", "https://new.vk.com/esn.uralfederal", "http://hsemsk.esnrussia.org", "https://vk.com/esnsftu", "www.esnboras.org", "http://www.circ.chalmers.se/", "www.esnsodertorn.org", "http://esnjonkoping.org/", "esnkalmar.org", "esnbth.org", "www.esn.studorg.liu.se", "esnlulea.org", "esnlund.org", "www.esnmalmo.org", "esn-orebro.org", "esnskovde.org", "", "www.esnsu.org", "http://visesn.org", "", "", "Esnljubljana.org", "www.erasmusljubljana.si", "", "", "www.umb.esn.sk", "cu.esn.sk", "www.eu.esn.sk", "", "stuba.esn.sk", "", "http://www.kosice.esn.sk/", "www.ukf.esn.sk", "http://www.sua.esn.sk/", "", "http://uniza.esn.sk/", "http://trnava.esn.sk", "http://cukurova.esnturkey.org", "http://esnturkey.org/akdeniz", "", "http://ankarauni.esnturkey.org", "esnturkey.org/gazi/", "", "http://metu.esnturkey.org/", "http://tedu.esnturkey.org/", "bilkent.esnturkey.org", "", "http://esnturkey.org/uludag/", "", "", "", "http://esogu.esnturkey.org/", "http://sdu.esnturkey.org/", "", "", "http://bahcesehir.esnturkey.org", "www.esnbogazici.com", "http://existanbul.esnturkey.org", "http://isik.esnturkey.org/", "http://esnturkey.org/itu/", "-", "http://marmara.esnturkey.org", "http://esnturkey.org/esnokan/", "www.esnytu.org", "https://www.facebook.com/ESN-DEU-372938016174054/?fref=ts", "http://ege.esnturkey.org/", "", "http://esnturkey.org/yasar/", "", "", "https://www.facebook.com/esnselcuk", "http://cbu.esnturkey.org/", "", "http://mersin.esnturkey.org", "", "https://www.facebook.com/esnsamsun55/?fref=ts", "trabzon.esnturkey.org", "http://yeditepe.esnturkey.org/", "http://belupgrade.esn.rs/", "http://novisad.esn.rs", "http://nis.esn.rs/"];
urls = urls.filter(function (url) {
    var expression = /[-a-zA-Z0-9@:%_\+.~#?&//=]{2,256}\.[a-z]{2,4}\b(\/[-a-zA-Z0-9@:%_\+.~#?&//=]*)?/gi;
    //kicking out the dirty shit and empty ones
    var regex = new RegExp(expression);
    return url.match(regex);
});
console.log('fetching number of sections: ' + urls.length);
// Queue a list of URLs
c.queue(urls);

var findByUrl = function (host) {
    for (var prop in nameUrlMap) {
        if (nameUrlMap[prop].indexOf(host)!=-1) return prop;
    }
};


var nameUrlMap = {
    "AT-GRAZ-TUN": "",
    "AT-GRAZ-UNI": "http://unigraz.esnaustria.org/welcome-esn-uni-graz",
    "AT-INNS-ESN": "http://innsbruck.esnaustria.org/",
    "AT-KLAG-ESN": "www.entree.at",
    "AT-KREM-ESN": "http://www.krems.esnaustria.org/",
    "AT-KUFS-ESN": "",
    "AT-LEOB-ESN": "",
    "AT-LINZ-ESN": "http://esnlinz.org",
    "AT-SALZ-UNI": "http://salzburg.esnaustria.org/",
    "AT-STEY-ESN": "",
    "AT-WIEN-BOK": "",
    "AT-WIEN-MUN": "http://oehmedwien.at/",
    "AT-WIEN-TEC": "http://technikum.esnaustria.org",
    "AT-WIEN-TUN": "www.buddynetwork.at",
    "AT-WIEN-UAS": "http://bfivienna.esnaustria.org",
    "AT-WIEN-UNI": "http://www.esnuniwien.com/",
    "AT-WIEN-WKW": "www.fhwien-wkw.esnaustria.org/",
    "AZ-BAKU-ESN": "baku.esn.az",
    "BA-SARA-ESN": "esn-bih.ba",
    "BE-ANTW-ESN": "esnantwerp.org",
    "BE-BRUS-EHS": "http://www.esnkulbrussels.org/",
    "BE-BRUS-ESN": "esnvubehb.org",
    "BE-BRUS-SLU": "",
    "BE-DIEP-ESN": "",
    "BE-GENT-ESN": "",
    "BE-KORT-ESN": "http://www.esnleonardokortrijk.org/",
    "BE-LEUV-ESN": "www.esnleuven.be",
    "BE-LIEG-ESN": "esnulg.org",
    "BE-LIEG-HEC": "http://esn.hec-ulg.be/",
    "BE-LIEG-HEL": "https://esnhelmo.wordpress.com/ or https://www.helmo.be/CMS/Profils/International/FR/ESN.aspx",
    "BE-LIEG-HEP": "",
    "BE-LLNE-ESN": "http://esnlln.org/",
    "BE-MONS-ESN": "None yet",
    "BE-MONS-UCL": "",
    "BG-BLAG-AUB": "none",
    "BG-PLOV-ESN": "plovdiv.esnbg.org",
    "BG-RUSE-ESN": "",
    "BG-SOFI-CTM": "",
    "BG-SOFI-ESN": "",
    "BG-SOFI-NBU": "",
    "BG-SOFI-UAC": "uaceg.esnbg.org",
    "BG-UNW-ESN": "http://unwe.esnbg.org/",
    "BG-VARN-ESN": "http://varna.esnbg.org/",
    "BG-VETA-ESN": "http://tarnovo.esnbg.org/",
    "CH-BASE-ESN": "",
    "CH-BERN-ESN": "www.bern.esn.ch",
    "CH-CHUR-HTW": "htwchur.esn.ch",
    "CH-FRIB-ESN": "fribourg.esn.ch",
    "CH-GENE-UNI": "http://geneva.esn.ch/",
    "CH-LAUS-XEP": "http://epfl.esn.ch/",
    "CH-LAUS-XUL": "",
    "CH-LUGA-ESN": "lugano.esn.ch",
    "CH-NEUC-ESN": "",
    "CH-OLTE-ESN": "olten.esn.ch",
    "CH-SGAL-ESN": "http://www.ressortinternational.ch/portfolio/buddysystem/",
    "CH-WAED-ESN": "http://winterthur.esn.ch",
    "CH-WINT-ESN": "/",
    "CH-ZURI-ETH": "http://zurich.esn.ch/",
    "CH-ZURI-UNI": "zurich.esn.ch",
    "CY-NICO-ESA": "www.esncy.org",
    "CZ-BRNO-ISC": "http://isc.muni.cz/",
    "CZ-BRNO-VUT": "www.isc.vutbr.cz",
    "CZ-CBUD-VST": "www.esnvste.cz",
    "CZ-HRKR-ESN": "www.buddyhk.cz",
    "CZ-LIBE-ESN": "http://www.esn-liberec.cz/",
    "CZ-MZLU-ESN": "http://iscmendelu.cz/",
    "CZ-OLOM-UPA": "http://esn.upol.cz",
    "CZ-OSTR-ISC": "http://isc.osu.cz/",
    "CZ-OSTR-VSB": "www.esnvsb.cz",
    "CZ-PARD-ESN": "http://http://esn.upce.cz/",
    "CZ-PILS-UWB": "http://www.esn.zcu.cz",
    "CZ-PRAG-CTU": "www.isc.cvut.cz",
    "CZ-PRAG-CUL": "http://esnculs.cz/",
    "CZ-PRAG-CUN": "www.ic-cuni.cz",
    "CZ-PRAG-ICT": "http://www.esnuct.cz/",
    "CZ-PRAG-VSE": "buddy.vse.cz",
    "CZ-USTI-ESN": "www.esn-usti.cz",
    "CZ-ZLIN-ESN": "www.buddysystem.utb.cz",
    "DE-AUGS-ESN": "http://augsburg.esn-germany.de/",
    "DE-BAYR-ESN": "http://bayreuth.esn-germany.de/",
    "DE-BERL-ESN": "",
    "DE-BOCH-ESN": "bochum@esngermany.org",
    "DE-BONN-ESN": "www.esn-bonn.de",
    "DE-BRAU-ISN": "http://braunschweig.esn-germany.de",
    "DE-DEGG-AKI": "http://www.aki-deggendorf.de/in/",
    "DE-DORT-ESN": "dortmund.esn-germany.de",
    "DE-DRES-HTW": "http://faranto.esn-germany.de/",
    "DE-DRES-TUN": "http://tu-dresden.esn-germany.de/?language=en",
    "DE-DUES-ESN": "www.duesseldorf.esn-germany.de",
    "DE-FRAN-ESN": "http://www.interstudis.eu/",
    "DE-FREI-ESN": "",
    "DE-FRMA-UNI": "http://unifrankfurt.esn-germany.de",
    "DE-GREI-ESN": "http://greifswald.esn-germany.de/",
    "DE-HALL-ESN": "halle.esn-germany.de",
    "DE-HAMB-HAR": "http://hamburg.esn-germany.de/de",
    "DE-HANN-ESN": "hannover.esn-germany.de",
    "DE-HEID-ESN": "www.esn-heidelberg.de",
    "DE-HILD-EOT": "hildesheim.esn-germany.de",
    "DE-INGO-ESN": "ingolstadt.esngermany.org",
    "DE-JENA-ESN": "http://jena.esn-germany.de/",
    "DE-KAIS-ESN": "www.step.wiwi.uni-kl.de",
    "DE-KARL-AKE": "www.ak-erasmus.de",
    "DE-KOLN-ESN": "koeln.esn-germany.de",
    "DE-LAND-IPA": "landau.esn-germany.de",
    "DE-MANN-ESN": "https://www.visum-mannheim.de/satellite4/",
    "DE-MUNI-MES": "http://mesa.esn-germany.de/",
    "DE-MUNI-TUM": "www.international.tum.de/tumi",
    "DE-POTS-LEI": "http://potsdam.esn-germany.de/",
    "DE-ROST-ESN": "www.lei-rostock.org",
    "DK-AARH-ESN": "",
    "DK-COPE-ESN": "http://esn-cph.dk",
    "DK-HADE-ESN": "",
    "DK-KOLD-ESN": "",
    "DK-LYNG-DTU": "www.esn-dtu.dk/",
    "DK-ODEN-ESN": "www.esnodense.dk",
    "EE-TALL-ESN": "http://esn.ee/tallinn",
    "EE-TALL-TLU": "https://www.esindus.ee/ic",
    "EE-TALL-TUT": "http://ic.tipikas.ee/",
    "EE-TART-ESN": "https://esn.ee/tartu",
    "ES-ALCA-ESN": "www,esn-uah.org",
    "ES-ALIC-ESN": "",
    "ES-ALME-ESN": "www.esnalmeria.org",
    "ES-BADA-ESN": "http://www.esnuex.org/",
    "ES-BARC-ESN": "http://esn-ub.org/",
    "ES-BARC-POM": "http://esnupf.org/",
    "ES-BARC-UAB": "http://esnuab.org",
    "ES-BARC-UPC": "http://www.esn-upc.org/",
    "ES-BILB-ESN": "http://esnbilbao.org/",
    "ES-CADI-ESN": "http://www.esncadiz.org/",
    "ES-CART-ESN": "www.esncartagena.org",
    "ES-CAST-ESN": "http://esncastellon.org/",
    "ES-CORU-ESN": "www.esncoruna.org",
    "ES-ELCH-ESN": "",
    "ES-GIRO-ESN": "www.udg.edu/esngirona ",
    "ES-GRAN-ESN": "www.esngranada.org",
    "ES-HULV-ESN": "",
    "ES-JAEN-ESN": "www.esnjaen.org",
    "ES-MADR-CA3": "http://esnuc3m.org/",
    "ES-MADR-RJC": "http://www.esnurjc.es/",
    "ES-MADR-UAM": "http://esnuam.org/",
    "ES-MADR-UCM": "Www.esnucm.org",
    "ES-MALA-ESN": "www.esnmalaga.org",
    "ES-MURC-ESN": "www.esnmurcia.es",
    "ES-OVIE-ESN": "www.esnoviedo.org",
    "ES-PALM-ESN": "",
    "ES-SALA-ESN": "http://esnsalamanca.com/",
    "ES-SEVI-ESN": "http://esnsevilla.org",
    "ES-UCLM-ESN": "http://www.esnuclm.org/",
    "ES-VALE-ESN": "http://esnuv.es",
    "ES-VALE-UPV": "http://esnvalenciaupv.es/",
    "ES-VALL-ESN": "http://www.esnuva.org/",
    "ES-VICA-ESN": "www.esnuax.org",
    "ES-VIGO-ESN": "www.esnvigo.org/satellite4",
    "ES-ZARA-ESN": "www.esnzaragoza.orh",
    "FI-HELS-HYY": "esnunihelsinki.com",
    "FI-HELS-KAN": "www.esn-helga.com",
    "FI-HELS-MET": "http://esn.metropolia.fi/",
    "FI-HELS-TKY": "esnaalto.org",
    "FI-JOEN-JYY": "http://esnjoensuu.fi/",
    "FI-JYVA-JYY": "http://www.esnjyvaskyla.org",
    "FI-KUOP-KIS": "www.esnkisa.eu",
    "FI-LAPP-ESN": "",
    "FI-OULU-OYY": "esnoulu.org",
    "FI-ROVA-LYY": "www.esnlapland.eu",
    "FI-TAMP-INT": "www.esninto.org",
    "FI-TAMP-TAM": "www.esnfint.org",
    "FI-TURK-AAU": "https://esnabo.org/",
    "FI-TURK-IAC": "esn-iac.org",
    "FI-TURK-TYY": "www.esnuniturku.fi",
    "FI-VAAS-ESN": "www.esnvaasa.net",
    "FR-AMIE-ESN": "amiens.ixesn.fr",
    "FR-AVIG-ESN": "http://avignon.ixesn.fr",
    "FR-BELF-ESN": "http://belfort-montbeliard.ixesn.fr/",
    "FR-BESA-AEI": "www.erasmus-besancon.com",
    "FR-BORD-ESN": "bordeaux.ixesn.fr",
    "FR-BRET-TEL": "",
    "FR-CLER-WOR": "http://worldtop.ixesn.fr/",
    "FR-COMP-UTC": "",
    "FR-CORT-ESN": "",
    "FR-DIJO-ESN": "http://dijon.ixesn.fr/",
    "FR-LILL-ESL": "http://esnlille.fr/satellite/",
    "FR-LYON-ESN": "www.lyon.ixesn.fr",
    "FR-MANS-ESN": "lemans.ixesn.fr",
    "FR-MARS-ESN": "marseille.ixesn.fr",
    "FR-MONT-ESN": "http://montpellier.ixesn.fr",
    "FR-NANC-ESN": "www.esnnancy.fr",
    "FR-NANC-GLO": "",
    "FR-NANT-AUT": "",
    "FR-NICE-ESN": "http://nice.ixesn.fr/",
    "FR-ORLE-ESN": "orleans.ixesn.fr",
    "FR-PARI-ASS": "http://paris.ixesn.fr/",
    "FR-PARI-EDC": "",
    "FR-PAUB-UPA": "",
    "FR-POIT-ESN": "http://poitiers.ixesn.fr/",
    "FR-PROV-AIX": "aix.ix.fr",
    "FR-REIM-ESN": "ereimsmus.eu",
    "FR-RENN-ESN": "http://rennes.ixesn.fr/",
    "FR-ROCH-ESN": "http://www.larochelle.ixesn.fr/",
    "FR-ROUE-ESN": "www.rouen.ixesn.fr",
    "FR-SCEA-ESN": "",
    "FR-STRA-ESN": "http://strasbourg.ixesn.fr/",
    "FR-TOUL-ASE": "http://www.toulouse.ixesn.fr",
    "FR-TOUR-ESN": "",
    "FR-TROY-ESC": "",
    "FR-VALE-ESN": "",
    "FR-VALE-INP": "http://valence.ixesn.fr/",
    "GB-ABER-ESN": "http://rgu.esnuk.org/",
    "GB-BANG-ESN": "",
    "GB-BRIS-ESN": "bristol.esnuk.org",
    "GB-CARD-ESN": "cardiff.esnuk.org",
    "GB-EDIN-HER": "http://hw.esnuk.org/",
    "GB-GLAS-CAL": "gcu.esnuk.org",
    "GB-GLAS-ESN": "uofg.esnuk.org",
    "GB-GLAS-STR": "",
    "GB-HERT-ESN": "herts.esnuk.org",
    "GB-KING-ESN": "http://kings.esnuk.org",
    "GB-LEED-ESN": "www.luu.org.uk/groups/interasoc/",
    "GB-LEIC-DMU": "",
    "GB-LIVE-ESN": "",
    "GB-LOND-ESN": "NA",
    "GB-LOND-IMP": "imperial.esnuk.org",
    "GB-LOND-WES": "http://westminster.esnuk.org/",
    "GB-OXFO-BRO": "",
    "GB-PLYM-ESN": "http://plymouth.esnuk.org/",
    "GB-PRES-ESN": "http://uclan.esnuk.org/",
    "GB-SOUT-ESN": "http://soton.esnuk.org/",
    "GB-UEA-NOR": "",
    "GE-TBIL-ISU": "",
    "GE-TBIL-UNI": "",
    "GR-ATHE-AUA": "",
    "GR-ATHE-ESN": "http://aueb.esnathens.gr/",
    "GR-ATHE-HAR": "",
    "GR-ATHE-KAP": "http://esnkapa.org/athens/",
    "GR-ATHE-PAN": "http://panteion.esngreece.gr/",
    "GR-ATHE-PIR": "http://esn.teipir.gr/",
    "GR-ATHE-TEI": "http://teiath.esngreece.gr/",
    "GR-CHAN-ESN": "http://tuc.esngreece.gr/",
    "GR-HERA-TEI": "",
    "GR-HERA-UOC": "http://uoc.esngreece.gr/",
    "GR-IOAN-ESN": "http://ioannina.esngreece.gr/",
    "GR-KOMO-ESN": "http://duth.esngreece.gr/",
    "GR-KOZA-TEI": "https://www.facebook.com/ESNTEIWM/?fref=ts",
    "GR-LAMI-ESN": "http://teiste.esngreece.gr/",
    "GR-LARI-ESN": "http://larissa.esngreece.gr/",
    "GR-MYTI-ESN": "",
    "GR-NTUA-ESN": "http://ntua.esngreece.gr/",
    "GR-PATR-ESN": "http://uopa.esngreece.gr/",
    "GR-PIRA-ESN": "http://unipi.esngreece.gr/",
    "GR-THES-AUT": "http://auth.esngreece.gr/",
    "GR-THES-ESN": "http://uom.esngreece.gr/",
    "GR-THES-TEI": "http://ateith.esngreece.gr/",
    "HR-DUBR-ESN": "www.esndubrovnik.hr",
    "HR-OSIJ-ESN": "",
    "HR-RIJE-ESN": "esn.hr",
    "HR-SPLI-ESN": "esnsplit.com",
    "HR-ZADA-ESN": "",
    "HR-ZAGR-ESN": "",
    "HU-BUPE-BKF": "",
    "HU-BUPE-BME": "https://www.esn.bme.hu/",
    "HU-BUPE-COR": "http://corvinus.esn.hu/",
    "HU-BUPE-ELT": "http://elte.esn.hu/",
    "HU-BUPE-IBS": "http://ibs.esn.hu/",
    "HU-BUPE-NUP": "http://nups.esn.hu/",
    "HU-BUPE-OBU": "http://obuda.esn.hu/",
    "HU-DEBR-ESN": "http://debrecen.esn.hu/",
    "HU-EGER-ESN": "eger.esn.hu",
    "HU-GODO-SZI": "szie.esn.hu",
    "HU-GYOR-ESN": "http://sze.esn.hu/",
    "HU-MISK-ESN": "http://miskolc.esn.hu/",
    "HU-PECS-ESN": "http://pecs.esn.hu/",
    "HU-SEMM-ESN": "http://semmelweis.esn.hu/",
    "HU-SZEG-ESN": "www.szeged.esn.hu",
    "HU-SZEK-KOD": "",
    "HU-VESZ-ESN": "",
    "IE-DUBL-UCD": "",
    "IE-GALW-ESN": "",
    "IE-MAYN-ESN": "",
    "IS-REJK-ESN": "esn.is",
    "IS-REJK-HAS": "N/A",
    "IT-ANCO-ESA": "http://www.esnancona.it",
    "IT-AQUI-ESN": "http://www.esnlaquila.it/",
    "IT-BARI-ESN": "www.esnbari.org",
    "IT-BENE-ESN": "",
    "IT-BERG-ESN": "http://www.esnbergamo.it/",
    "IT-BOCC-ESN": "www.esnbocconi.it",
    "IT-BOLO-ESN": "http://www.esnbologna.org/",
    "IT-BRES-ESN": "http://www.esnbrescia.it/",
    "IT-CAGL-ESN": "www.esncagliari.org ",
    "IT-CAME-AUR": "www.esncamerino.it",
    "IT-CAST-ESN": "www.esncastellanza.it",
    "IT-CATA-ASE": "http://www.esncatania.it/",
    "IT-COSE-ESN": "www.esncosenza.org",
    "IT-CTNZ-ESN": "www.esncatanzaro.com",
    "IT-FERR-ESN": "www.esnferrara.org",
    "IT-FLOR-ESN": "http://www.esnflorentia.it",
    "IT-FOGG-ESN": "www.esnfoggia.it",
    "IT-GENO-ESN": "",
    "IT-LECC-LIS": "www.erasmuslecce.it",
    "IT-MACE-ESN": "www.esnmacerata.it",
    "IT-MESS-ESN": "http://www.esn-messina.it",
    "IT-MILA-BIC": "http://www.esnbicocca.it/bicocca",
    "IT-MILA-IUL": "http://www.esniulm.it",
    "IT-MILA-POL": "http://www.esnpolimi.it/",
    "IT-MILA-STA": "http://www.esnmilanostatale.it/",
    "IT-MILA-UCA": "www.esnunicatt.it",
    "IT-MODE-ESN": "www.esnmodena.it",
    "IT-NAPO-ESN": "",
    "IT-NOVA-ESN": "http://piemonteorientale.org/",
    "IT-PADO-ESN": "http://sat4.esnpadova.eu/?q=events/feed",
    "IT-PALE-ESN": "",
    "IT-PARM-ASI": "assi.unipr.it",
    "IT-PAVI-ESN": "http://www.esnpavia.org/",
    "IT-PERU-PEP": "http://www.perugiaerasmusproject.eu",
    "IT-PESC-ASE": "www.esnchietipescara.eu",
    "IT-PISA-ESN": "www.esnpisa.it",
    "IT-POTE-ESN": "http://www.esnsuigenerisbas.it/",
    "IT-RECA-ESN": "http://www.esnreggiocalabria.org/",
    "IT-RIMI-ESN": "www.esnrimini.it",
    "IT-ROMA-ASE": "",
    "IT-ROMA-LUI": "http://www.esnromaluiss.it/",
    "IT-ROMA-TRE": "http://www.esnroma3.com/",
    "IT-SALE-ESN": "http://www.esnsalerno.it/",
    "IT-SASS-ESN": "",
    "IT-SIEN-GES": "",
    "IT-TAVA-ESN": "www.esnnaseudine.it",
    "IT-TERA-ESN": "esnteramo.eu",
    "IT-TREN-ESN": "www.esntrento.it",
    "IT-TRIE-ESN": "http://esntrieste.it/",
    "IT-VENE-MAM": "",
    "IT-VERO-ESN": "http://www.ase-esnverona.it/",
    "LI-VADU-ESN": "www.esn.li",
    "LT-KAUN-ESN": "http://ktu.esnlithuania.org/",
    "LT-KAUN-KK1": "http://esnlithuania.org/sections/esn-kk",
    "LT-KAUN-LSU": "",
    "LT-KAUN-SMU": "",
    "LT-KAUN-VMU": "vmu.esnlithuania.org",
    "LT-KLAI-ESN": "",
    "LT-SUSA-ESN": "",
    "LT-VILN-ESN": "vu.esnlithuania.org",
    "LT-VILN-ISLB": "",
    "LT-VILN-ISM": "http://ism.esnlithuania.org",
    "LT-VILN-LEU": "http://leu.lt/lt/esn-leu/esn-naujienos.html",
    "LT-VILN-MRU": "http://mru.esnlithuania.org/",
    "LT-VILN-SMK": "",
    "LT-VILN-VDK": "http://vdk.esnlithuania.org/",
    "LT-VILN-VGTU": "",
    "LU-LUXE-ESN": "www.esn.lu",
    "LV-JELG-LLU": "https://www.facebook.com/Erasmusjelgava/",
    "LV-LIEP-ESN": "",
    "LV-RIGA-ESN": "http://riga.esn.lv/",
    "LV-VALM-ESN": "https://www.facebook.com/ESNvalmiera/?ref=bookmarks",
    "MK-SKOP-ESN": "",
    "MK-SKOP-UAC": "/",
    "MT-MALT-ESN": "esnmalta.org",
    "NL-AMST-ISN": "http://isn-amsterdam.nl/",
    "NL-AMST-VUN": "http://esnvuamsterdam.nl/",
    "NL-BRED-ESN": "www.esn-breda.nl",
    "NL-DELF-ESN": "www.esn-delft.nl/",
    "NL-DIEM-INH": "",
    "NL-ENSC-TWE": "esntwente.nl",
    "NL-GRON-WIN": "www.esn-groningen.nl",
    "NL-HAAR-ESN": "esnhaarlem.nl",
    "NL-LEEU-ESN": "www.esn-leeuwarden.com",
    "NL-LEID-ESN": "www.isnleiden.com",
    "NL-MAAS-ESN": "isn-maastricht.nl",
    "NL-ROTT-ESN": "www.esn-rotterdam.nl",
    "NL-ROTT-INH": "http://www.esnrotterdam.nl",
    "NL-TILB-ESN": "www.iesntilburg.nl",
    "NL-UTRE-ESN": "www.esn-utrecht.nl",
    "NL-WAGE-ESN": "http://ixesn-wageningen.nl/",
    "NO-ALTA-ESN": "https://www.facebook.com/groups/121550639157/?fref=ts",
    "NO-AS-ESN": "http://www.as.esn.no/",
    "NO-BERG-ESN": "http://www.bergen.esn.no/",
    "NO-KGAR-AGD": "http://agder.esn.no",
    "NO-MOLD-ESN": "www.molde.esn.no",
    "NO-OSLO-UNI": "http://www.oslo.esn.no/",
    "NO-STAV-ESN": "",
    "NO-TRON-ESN": "www.trondheim.esn.no",
    "PL-BIAL-ESN": "http://pb.esn.pl/",
    "PL-BIAL-UWB": "http://uwb.esn.pl",
    "PL-BYDG-ESN": "http://www.ukw.edu.pl/jednostka/erasmus_student_network/",
    "PL-CZES-ESN": "http://pcz.esn.pl",
    "PL-GDAN-POL": "http://gdansk.esn.pl/",
    "PL-GDAN-UNG": "http://ug.esn.pl",
    "PL-GDYN-ESN": "",
    "PL-GLIW-SUT": "http://sut.esn.pl/",
    "PL-KATO-ACE": "",
    "PL-KATO-ESN": "",
    "PL-KRAK-ACE": "http://uek.esn.pl/",
    "PL-KRAK-AGH": "http://agh.esn.pl/",
    "PL-KRAK-POL": "http://www.pk.esn.pl/",
    "PL-KRAK-UNJ": "http://uj.esn.pl/",
    "PL-KRAKO-ESN": "",
    "PL-LODZ-EYE": "eye.esn.pl",
    "PL-LODZ-UNL": "lodz.esn.pl",
    "PL-LUBL-LUT": "http://www.lut.esn.pl/",
    "PL-LUBL-UMC": "umcs.esn.pl",
    "PL-OLSZ-UWM": "http://uwm.esn.pl/pl",
    "PL-OPOL-ESN": "",
    "PL-POZN-ESN": "http://esnpoznan.pl/",
    "PL-POZN-UAM": "www.uam.esn.pl ",
    "PL-POZN-UEP": "",
    "PL-POZN-UPP": "NA",
    "PL-POZN-WSB": "we dont have",
    "PL-SZCZ-ESN": "http://szczecin.esn.pl/",
    "PL-TORU-UMK": "",
    "PL-WARS-ACM": "",
    "PL-WARS-COC": "cc.esn.pl",
    "PL-WARS-KOZ": "-",
    "PL-WARS-LAZ": "lazarski.esn.pl",
    "PL-WARS-SEC": "esnsgh.pl",
    "PL-WARS-SGG": "http://sggw.esn.pl/",
    "PL-WARS-SWP": "swps.esn.pl",
    "PL-WARS-UKS": "www.uksw.esn.pl",
    "PL-WARS-UNW": "www.uw.esn.pl",
    "PL-WARS-WPW": "www.pw.esn.pl",
    "PL-WROC-PWR": "http://pwr.esn.pl/",
    "PL-WROC-UE1": "http://uewroclaw.esn.pl/",
    "PL-WROC-UPW": "http://up.esn.pl/",
    "PL-WROC-UWR": "www.facebook.com/esn.uwr",
    "PT-AVEI-ESN": "http://www.esnaveiro.org",
    "PT-BRAG-ESN": "www.esnbraganca.org",
    "PT-CAST-ESN": "",
    "PT-COIM-ASE": "http://www.esncoimbra.org/",
    "PT-COVI-ESN": "www.esn-covilha.org",
    "PT-EVOR-ESN": "www.esnevora.org",
    "PT-FARO-UAL": "http://www.esnalgarve.org/",
    "PT-FUNC-ESN": "www.esnmadeira.org",
    "PT-LEIR-ESN": "http://esnleiria.com/",
    "PT-LISB-ESN": "http://esnlisboa.org/",
    "PT-MINH-UOM": "http://www.esnminho.org/",
    "PT-PORT-ESN": "esnporto.org",
    "PT-TOMA-ESN": "",
    "PT-VILA-UTA": "esnutad.org",
    "RO-ALBA-ESN": "http://alba-iulia.esn.ro/",
    "RO-BRAS-ESN": "",
    "RO-BUCH-ESN": "www.ase-bucharest.esn.ro",
    "RO-BUCH-UNI": "http://unibucharest.esn.ro/",
    "RO-CLUJ-ESN": "http://cluj-napoca.esn.ro/",
    "RO-CONS-ESN": "http://esn.ro/constanta/",
    "RO-CRAI-ESN": "http://craiova.esn.ro",
    "RO-IASI-ESN": "http://iasi.esn.ro/",
    "RO-SIBI-ESN": "sibiu.esn.ro",
    "RO-TIMI-ESN": "www.timisoara.esn.ro",
    "RU-EKAT-ESN": "https://new.vk.com/esn.uralfederal",
    "RU-MOSC-ESN": "http://hsemsk.esnrussia.org",
    "RU-STPB-LTU": "https://vk.com/esnsftu",
    "SE-BORA-ESN": "www.esnboras.org",
    "SE-GOTE-CIR": "http://www.circ.chalmers.se/",
    "SE-HUDD-ESN": "www.esnsodertorn.org",
    "SE-JONK-ESN": "http://esnjonkoping.org/",
    "SE-KALM-ESN": "esnkalmar.org",
    "SE-KARL-BTH": "esnbth.org",
    "SE-LINK-ESN": "www.esn.studorg.liu.se",
    "SE-LULE-ESN": "esnlulea.org",
    "SE-LUND-ESN": "esnlund.org",
    "SE-MALM-INT": "www.esnmalmo.org",
    "SE-OREB-ESN": "esn-orebro.org",
    "SE-SKOV-ESN": "esnskovde.org",
    "SE-STOC-KTH": "",
    "SE-STOC-SUS": "www.esnsu.org",
    "SE-VAXJ-ESN": "http://visesn.org",
    "SI-KOPE-PRI": "",
    "SI-KRAN-ESN": "",
    "SI-LJUB-ESN": "Esnljubljana.org",
    "SI-LJUB-FDV": "www.erasmusljubljana.si",
    "SI-MARI-ESN": "",
    "SI-MARI-SOU": "",
    "SK-BANS-UMB": "www.umb.esn.sk",
    "SK-BRAT-COM": "cu.esn.sk",
    "SK-BRAT-EUB": "www.eu.esn.sk",
    "SK-BRAT-PEU": "",
    "SK-BRAT-STU": "stuba.esn.sk",
    "SK-BRAT-VSM": "",
    "SK-KOSI-ESN": "http://www.kosice.esn.sk/",
    "SK-NITR-UKF": "www.ukf.esn.sk",
    "SK-NTRA-ESN": "http://www.sua.esn.sk/",
    "SK-PRES-UNI": "",
    "SK-RUZO-UNZ": "http://uniza.esn.sk/",
    "SK-TRNA-ESN": "http://trnava.esn.sk",
    "TR-ADAN-ESN": "http://cukurova.esnturkey.org",
    "TR-ANKA-AKD": "http://esnturkey.org/akdeniz",
    "TR-ANKA-ATI": "",
    "TR-ANKA-ESN": "http://ankarauni.esnturkey.org",
    "TR-ANKA-GAZ": "esnturkey.org/gazi/",
    "TR-ANKA-HAC": "",
    "TR-ANKA-MET": "http://metu.esnturkey.org/",
    "TR-ANKA-TED": "http://tedu.esnturkey.org/",
    "TR-BILK-ESN": "bilkent.esnturkey.org",
    "TR-BOLU-IBU": "",
    "TR-BURS-ULU": "http://esnturkey.org/uludag/",
    "TR-CANA-ESN": "",
    "TR-ELAZ-ESN": "",
    "TR-ESKI-ANA": "",
    "TR-ESKI-ESN": "http://esogu.esnturkey.org/",
    "TR-ISPA-SDU": "http://sdu.esnturkey.org/",
    "TR-ISTA-ARE": "",
    "TR-ISTA-AYD": "",
    "TR-ISTA-BAH": "http://bahcesehir.esnturkey.org",
    "TR-ISTA-BOG": "www.esnbogazici.com",
    "TR-ISTA-EXI": "http://existanbul.esnturkey.org",
    "TR-ISTA-ISK": "http://isik.esnturkey.org/",
    "TR-ISTA-ITU": "http://esnturkey.org/itu/",
    "TR-ISTA-MAL": "-",
    "TR-ISTA-MAR": "http://marmara.esnturkey.org",
    "TR-ISTA-OKA": "http://esnturkey.org/esnokan/",
    "TR-ISTA-YIL": "www.esnytu.org",
    "TR-IZMI-DEU": "https://www.facebook.com/ESN-DEU-372938016174054/?fref=ts",
    "TR-IZMI-EGE": "http://ege.esnturkey.org/",
    "TR-IZMI-IUE": "",
    "TR-IZMI-YAS": "http://esnturkey.org/yasar/",
    "TR-KHAS-ESN": "",
    "TR-KOCA-ESN": "",
    "TR-KONY-SEL": "https://www.facebook.com/esnselcuk",
    "TR-MANI-ESN": "http://cbu.esnturkey.org/",
    "TR-MERS-CAG": "",
    "TR-MERS-ESN": "http://mersin.esnturkey.org",
    "TR-NISA-ESN": "",
    "TR-SAMS-ESN": "https://www.facebook.com/esnsamsun55/?fref=ts",
    "TR-TRAB-ESN": "trabzon.esnturkey.org",
    "TR-YEDI-ESN": "http://yeditepe.esnturkey.org/",
    "YU-BELG-UPG": "http://belupgrade.esn.rs/",
    "YU-NOVI-SAD": "http://novisad.esn.rs",
    "YU-SERB-ESN": "http://nis.esn.rs/"
};